__author__ = 'Yee.Ch'


from mongoengine import *

class MainMsg(Document):

    COMPANY_TITLE = 'J&D Helpdesk Solutions'
    BASE_TITLE = 'J&D Helpdesk'
    LOGIN_TITLE = 'Login'
    REGISTER_TITLE = 'Registration'
    DASHBOARD_TITLE = 'Dashboard'
    PROFILE_TITLE = 'Profile'
    TEMPLATE_TITLE = 'template_title'
    FRIENDSHIP_TITLE = 'FriendShip'
    LOGIN_PAGE_TITLE = 'Login'
    REGISTER_PAGE_TITLE = 'Registration'
    POST = 'POST'
    TEMPLATE_TITLE = 'template_title'
    SUCCESS_ = 'success'
    FORM = 'form'
    CURRENT_PAGE = '/'
    TO_LOGIN_PAGE = '/login/'
    TO_HOME_PAGE = '/home/'
    TO_ACTIVATE_PAGE = '/activate/'
    TO_REGISTER_PAGE = '/register/'
    LOGIN_PAGE = 'login.html'
    REGISTER_PAGE = 'register.html'
    CURRENT_DATE_TIME = 'current_datetime'
    TITLE = 'title'
    EMAIL_PATH = "/Email.txt"
    REQUIRED = 'required'
    CLASS = 'class'
    PLACEHOLDER = 'placeholder'
    AUTOFOCUS = 'autofocus'
    ONFOCUS = 'onfocus'
    CURSORTOEND = 'this.value = this.value'
    STYLE = 'style'
    FORM_CONTROL_CLASS = 'form-control'
    FORM_CONTROL_CLASS_BUTTON ='radio-custom'
    BORDER_RED = 'border-color:red;'
    UNKNOWN_ERROR = 'Unknown error'